import { createFileRoute } from "@tanstack/react-router";
import { EventStream } from "@/components/rail/EventStream";

export const Route = createFileRoute("/events")({
  head: () => ({
    meta: [
      { title: "Live Event Stream — RailPulse AI" },
      {
        name: "description",
        content:
          "Searchable audit trail of movement, infrastructure and AI decision events generated by the RailPulse corridor simulation.",
      },
      { property: "og:title", content: "Live Event Stream — RailPulse AI" },
      {
        property: "og:description",
        content: "Every movement, infra and AI decision event on the corridor, in one audit trail.",
      },
    ],
  }),
  component: EventsPage,
});

function EventsPage() {
  return (
    <div className="space-y-5">
      <div>
        <h1 className="font-display text-xl font-semibold">Live Event Stream</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Chronological audit trail of every movement report, infrastructure change and AI decision.
          Filter by channel or search by train number.
        </p>
      </div>
      <EventStream height="max-h-[calc(100vh-16rem)]" />
    </div>
  );
}
