/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as TrainsIndexRouteImport } from './routes/trains.index'
import { Route as TrainsTrainIdRouteImport } from './routes/trains.$trainId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainsIndexRoute = TrainsIndexRouteImport.update({
  id: '/trains/',
  path: '/trains/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainsTrainIdRoute = TrainsTrainIdRouteImport.update({
  id: '/trains/$trainId',
  path: '/trains/$trainId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/simulator': typeof SimulatorRoute
  '/trains/$trainId': typeof TrainsTrainIdRoute
  '/trains/': typeof TrainsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/simulator': typeof SimulatorRoute
  '/trains/$trainId': typeof TrainsTrainIdRoute
  '/trains': typeof TrainsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/simulator': typeof SimulatorRoute
  '/trains/$trainId': typeof TrainsTrainIdRoute
  '/trains/': typeof TrainsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/simulator' | '/trains/$trainId' | '/trains/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/simulator' | '/trains/$trainId' | '/trains'
  id: '__root__' | '/' | '/simulator' | '/trains/$trainId' | '/trains/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SimulatorRoute: typeof SimulatorRoute
  TrainsTrainIdRoute: typeof TrainsTrainIdRoute
  TrainsIndexRoute: typeof TrainsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trains/': {
      id: '/trains/'
      path: '/trains'
      fullPath: '/trains/'
      preLoaderRoute: typeof TrainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trains/$trainId': {
      id: '/trains/$trainId'
      path: '/trains/$trainId'
      fullPath: '/trains/$trainId'
      preLoaderRoute: typeof TrainsTrainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SimulatorRoute: SimulatorRoute,
  TrainsTrainIdRoute: TrainsTrainIdRoute,
  TrainsIndexRoute: TrainsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
